version: "3.8"

services:
  app:
    image: node:20.13.1-alpine
    container_name: t3-app
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/ai_gourmet_navigator?schema=public"
    command: sh -c "npm install && npm run dev"

  db:
    image: postgres:14.12
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ai_gourmet_navigator
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
